version: '3.7'

services:
  website:
    build: .
    container_name: website
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl/bot:/etc/nginx/ssl/bot
      - /etc/letsencrypt/live/leksus.net/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /etc/letsencrypt/live/leksus.net/fullchain.pem:/etc/nginx/ssl/fullchain.pem
